### ISSUE TITLE
Where are you learning from?

### ISSUE THREAD

**Issue by fengyuli-dev** [BabyChouSr/CrackingTheCodingInterview#1]
# Hellooooo!
It happens that I'm also going to learn more about data structures / algorithms and their implementation in C++ in the upcoming semester. May I ask for any recommendations of online materials? Like from which source are your chapters (in this repo) organized?

Maybe you can read this as you can pronounce Beijing Duck so accurately roughly a year ago.:smile:
你好呀，想知道你这个repository里的代码是参照哪个网站/哪本书写的！

**Comment by BabyChouSr** [comment]
### HI!

That's super cool that you're going to be studying DS/algorithms also! This repository is following the chapters from Cracking the Coding Interview 6th Edition by Gayle Laakmann McDowell. After this book, I plan to start doing LeetCode, HackerRank, InterviewCake, and many other online interview prep website's coding questions.

If you want, we could talk more about coding problems and the interview process on Discord at BabyChou#6503.

And, yes, I could read that Chinese (even though it's simplified)! We should totally hop on a call one day to catch up :)
